#!/usr/bin/perl
#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer Enterprise
# All rights are reserved
#

use esmith::Build::CreateLinks qw(:all);


#
# nethserver-alerts-update event
#
event_templates('nethserver-alerts-update', qw(
   /etc/collectd.d/threshold.conf
   /etc/collectd.d/filter.conf
   /etc/collectd.d/ping.conf
));

event_templates('nethserver-backup-data-update', qw(
   /etc/collectd.d/threshold.conf
   /etc/collectd.d/filter.conf
));

event_templates('nethserver-register-save', qw(
  /etc/collectd.d/threshold.conf
));

event_templates('nethserver-collectd-save', qw(
  /etc/collectd.d/threshold.conf
  /etc/collectd.d/filter.conf
));

event_templates('nethserver-collectd-update', qw(
  /etc/collectd.d/threshold.conf
  /etc/collectd.d/filter.conf
));

event_actions('nethserver-alerts-update', qw(
    initialize-default-databases        00
));

event_actions('interface-update', qw(
    nethserver-alerts-reset-wan   03
));

event_services('nethserver-alerts-update', qw(
    collectd restart
));

event_services('nethserver-register-save', qw(
    collectd restart
));

event_actions('wan-uplink-update', qw(
    nethserver-alerts-lsm-update 60
));

#
# nethserver-alerts-save event
#

event_templates('nethserver-alerts-save', qw(
   /etc/collectd.d/threshold.conf
   /etc/collectd.d/filter.conf
   /etc/collectd.d/ping.conf
));

event_services('nethserver-alerts-save', qw(
    collectd restart
));

event_actions('nethserver-alerts-save', qw(
    nethserver-alerts-update-alertsdb   02
));


#
# nethserver-subscription-save event
#

event_templates('nethserver-subscription-save', qw(
   /etc/collectd.d/threshold.conf
));

event_services('nethserver-subscription-save', qw(
    collectd restart
));

