#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use esmith::ConfigDB;
use NethServer::BackupData;

my $conf = esmith::ConfigDB->open || die("Could not open config db\n");
my $backup = $conf->get('backup-data');
my $logFile = $backup->prop('LogFile') || '/var/log/last-backup.log';
my $collectdLogFile = '/var/log/last-backup-collectd.log';

open(my $fh, "<", $logFile) || die("Could not open log file\n");
open(my $fhCollectd, ">", $collectdLogFile) || die("Could not open log file\n");

my $filter = 0;
while (my $row = <$fh>) {
    chomp($row);

    $filter = ($filter ^ ($row =~ /^----/));

    print $fhCollectd $row. "\n" if $filter && $row !~ /^----/;
}

close($fh) || die("Could not close log file\n");

close($fhCollectd) || die("Could not close log file\n");

exit 0;
