#!/bin/bash
#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer Enterprise
# All rights are reserved
#

# Skip event name
shift;

STATE=${1}
NAME=${2}
PREVSTATE=${15}
TIMESTAMP=${16}

hostname=$(hostname)
severity=""

if [ ${STATE} = ${PREVSTATE} ]; then
    exit 0
fi

if [ ${STATE} = up ]; then
  severity="okay"
else
  severity="failure"
fi

echo -e "PUTNOTIF host=$hostname plugin=wan plugin_instance=$NAME type=$STATE severity=$severity time=$TIMESTAMP message=\"$NAME is $STATE\"\n" | nc -U /var/run/collectd.sock &>/dev/null

exit 0;
