#!/bin/bash

SYSTEMID=$(/sbin/e-smith/config getprop nethupdate SystemID)

ALERTSDBJSON=$(/usr/bin/curl -s "https://my.nethesis.it/api/customalerts/configuration?system_key=$SYSTEMID")
RES1=$?

if [[ $RES1 == 0 ]] ; then
    # create temp db file
    TMPDB=$(mktemp)
    /sbin/e-smith/db $TMPDB setjson "$ALERTSDBJSON"
    RES2=$?

    # compare temp db file with alerts db
    if [[ $(/sbin/e-smith/db $TMPDB show | md5sum) != $(/sbin/e-smith/db alerts show | md5sum) ]] ; then
        # temp db differs from alerts db
        mv $TMPDB /var/lib/nethserver/db/alerts
    else
        # db isn't changed
        rm $TMPDB
    fi
    if [ -f /var/lib/nethserver/db/alerts ]; then
        /usr/bin/chown root:adm /var/lib/nethserver/db/alerts
    fi
fi

if [[ $RES1 == 0 && $RES2 == 0 ]]; then
    exit 0
else
    exit 1
fi
