#!/bin/bash

SYSTEMID=$(/sbin/e-smith/config getprop nethupdate SystemID)

ALERTSDBJSON=$(/usr/bin/curl -s "https://my.nethesis.it/api/customalerts/configuration?system_key=$SYSTEMID")
RES1=$?

if [[ $RES1 == 0 ]] ; then
    # Clean old alerts db
    /sbin/e-smith/db alerts show | grep '^[0-9]*=.*$' | cut -d= -f1 | xargs -I SUB /sbin/e-smith/db alerts delete SUB
    RES2=$?

    # Use JSON to create again alerts db
    /sbin/e-smith/db alerts setjson "$ALERTSDBJSON"
    RES3=$?

    # Set ping hosts to collectd config
    for PINGHOST in $(/sbin/e-smith/db alerts show | grep '^[0-9]*=ping$' | cut -d= -f1 | xargs -I SUB /sbin/e-smith/db alerts getprop SUB Instance | sort -u) ; do
        PINGHOSTS="$PINGHOSTS,$PINGHOST"
    done
    /sbin/e-smith/db configuration setprop collectd PingHosts "$(echo $PINGHOSTS | sed 's/^,//')"
fi

if [[ $RES1 == 0 && $RES2 == 0 && $RES3 == 0 ]]; then
    exit 0
else
    exit 1
fi
